# Allows page scroll (instead of scrolling through command history)
# Also allows panes to be resized by dragging
set -g mouse on

# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Auto renumber windows - e.g. if you have 1 2 3 and delete 2, it becomes 1 2 (as opposed to 1 3)
set-option -g renumber-windows on

# Remap split window keys
bind "|" split-window -h
bind "_" split-window -v

# Remap window navigation keys
bind "h" previous-window
bind "l" next-window
bind "-" last-window

# Clock mode
setw -g clock-mode-colour green # display the time with Prefix-t

# Statusbar
set -g status-position top
set -g status-justify left
set -g status-style 'fg=green'

set -g status-left '' # Don't show session name
set -g status-left-length 10

set -g status-right-style 'fg=white bold'
set -g status-right '%d/%m/%Y %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=green'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=green bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=green]#F '

setw -g window-status-bell-style 'fg=white bg=green bold'

# Messages
set -g message-style 'fg=white bg=black bold'
